import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar/Navbar";
import { ReactQueryProvider } from "./providers/ReactQueryProvider";
import { ReduxStoreProvider } from "./providers/ReduxStoreProvider";
import { CheckAuthProvider } from "./providers/CheckAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxStoreProvider>
          <CheckAuthProvider>
            <ReactQueryProvider>
              <Navbar />
              {children}
            </ReactQueryProvider>
          </CheckAuthProvider>
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
